[project]
name = "steamsensepro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Juan Miguel Galan Olivares", email = "juangalanolivarea99@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.61.1",
]

[project.scripts]
steamsensepro = "steamsensepro:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
